delete from AREADECONOCIMIENTOENTITY;
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('convallis tortor', 'Human Resources', 80);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('fusce', 'Human Resources', 81);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('ante', 'Engineering', 82);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('augue', 'Human Resources', 83);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('mattis odio', 'Support', 84);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('velit vivamus', 'Business Development', 85);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('faucibus', 'Engineering', 86);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('velit eu', 'Human Resources', 87);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('dapibus', 'Marketing', 88);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('sit amet', 'Accounting', 89);
