delete from EMPLEADOENTITY;
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Job', 75.8, 3,50);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Cyrille', 99.5, 2,51);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Kin', 75.3, 2,52);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Ellis', 6.3, 1,53);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Howard', 43.9, 3,54);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Dorey', 62.1, 1,55);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Tyrus', 4.9, 3,56);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Gino', 84.6, 3,57);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Alessandro', 91.5, 1,58);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Dalli', 41.6, 3,59);
