delete from HojaDeVidaEntity;
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (50, 'Felic Prate', 'Librarian', 'Integrated oil Companies', 'Universidade de Aveiro');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (51, 'Karla Winspear', 'VP Quality Control', 'Other Specialty Stores', 'University of East Srarajevo');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (52, 'Jack Mumbray', 'Senior Financial Analyst', 'n/a', 'Instituto Politécnico do Cávado e do Ave');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (53, 'Trina Bridgstock', 'Health Coach II', 'Real Estate', 'Elizabethtown College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (54, 'Bunnie Campana', 'Environmental Tech', 'Forest Products', 'Universidad Autónoma Metropolitana - Azcapotzalco');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (55, 'Misty Liveing', 'Chief Design Engineer', 'Commercial Banks', 'Adventist University of Africa');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (56, 'Tremain Bish', 'Programmer Analyst IV', 'Medical/Dental Instruments', 'St. Lawrence University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (57, 'Gael Welfair', 'Paralegal', 'Television Services', 'Tashkent Pharmaceutical Institute');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (58, 'Coralyn Slowgrove', 'Developer III', 'Hotels/Resorts', 'Ouachita Baptist University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (59, 'Annnora Clere', 'Food Chemist', 'Broadcasting', 'Botswana International University of Science & Technology');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (60, 'Herrick Beininck', 'Safety Technician IV', 'Metal Fabrications', 'Institute of Industrial Electronics Engineering');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (61, 'Anabelle Scoyles', 'VP Product Management', 'n/a', 'LICCSAL Business College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (62, 'Coretta Fairebrother', 'Web Developer IV', 'Major Banks', 'South Asian University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (63, 'Auria Pittway', 'Mechanical Systems Engineer', 'Major Chemicals', 'Maharishi Dayanand University, Rohtak (Haryana )');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (64, 'Karen Nosworthy', 'Software Consultant', 'Catalog/Specialty Distribution', 'Rose-Hulman Institute of Technology');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (65, 'Cristie Heiden', 'Nuclear Power Engineer', 'Television Services', 'University of Texas at Dallas');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (66, 'Germaine Carlyle', 'Desktop Support Technician', 'Containers/Packaging', 'Kalmyk State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (67, 'Annadiana Selbach', 'Staff Scientist', 'Power Generation', 'Universidad de San Carlos de Guatemala');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (68, 'Gerrard Stanley', 'Developer II', 'Containers/Packaging', 'Khabarovsk State Academy of Economics and Law');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (69, 'Sabina Simonelli', 'VP Quality Control', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', 'Illinois State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (70, 'Gilbertine Stubbings', 'General Manager', 'Military/Government/Technical', 'Université des Sciences et Technologies de Lille (Lille I)');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (71, 'Armstrong Fishpoole', 'Nurse', 'Marine Transportation', 'Indian Institute of Technology, Guwahati');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (72, 'Merle Stenett', 'Structural Engineer', 'Industrial Machinery/Components', 'Katholische Universität Eichstätt');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (73, 'Othilie Cammacke', 'Assistant Media Planner', 'n/a', 'Medical University of South Carolina');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (74, 'Law Diess', 'Teacher', 'Specialty Chemicals', 'Kokugakuin University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (75, 'Alonzo Shynn', 'Structural Analysis Engineer', 'Computer Software: Prepackaged Software', 'Institute of Teachers Education, Tengku Ampuan Afzan');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (76, 'Gerardo Maxwaile', 'Software Consultant', 'Major Chemicals', 'Norton University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (77, 'Francisco Varga', 'Help Desk Operator', 'Air Freight/Delivery Services', 'Universidade Catolica Portuguesa');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (78, 'Dacia Mapes', 'Project Manager', 'Diversified Commercial Services', 'Aristotle University of Thessaloniki');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (79, 'Myrwyn Reneke', 'Structural Analysis Engineer', 'Packaged Foods', 'Joetsu University of Education');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (80, 'Georgette Camm', 'Media Manager II', 'Real Estate', 'Dominica State College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (81, 'Rochelle Caccavari', 'Associate Professor', 'n/a', 'Debre Birhan University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (82, 'Darby Bunker', 'Senior Cost Accountant', 'Property-Casualty Insurers', 'Pitzer College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (83, 'Fred Behrend', 'Project Manager', 'Major Banks', 'Hogeschool van Amsterdam');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (84, 'Pia Presho', 'Desktop Support Technician', 'Oilfield Services/Equipment', 'University of Cape Town');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (85, 'Elianora Vickers', 'Human Resources Manager', 'n/a', 'Pontificio Ateneo Antonianum');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (86, 'Jessika Wendover', 'Quality Engineer', 'Electric Utilities: Central', 'City University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (87, 'Revkah Mityushin', 'Help Desk Operator', 'Homebuilding', 'Siberian State Industrial University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (88, 'Farrel Hatry', 'Actuary', 'Investment Bankers/Brokers/Service', 'Wake Forest University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (89, 'Hillery Lagneaux', 'Software Engineer II', 'Oil & Gas Production', 'Marij State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (90, 'Simone Bygott', 'Data Coordiator', 'Major Banks', 'Emmaus Bible College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (91, 'Moreen Garralts', 'Community Outreach Specialist', 'Savings Institutions', 'Maseno University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (92, 'Mick Maltman', 'Operator', 'n/a', 'Menlo College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (93, 'Mariana Bignold', 'Marketing Manager', 'Major Pharmaceuticals', 'Muskingum College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (94, 'Emmit Filipczynski', 'Senior Quality Engineer', 'Finance: Consumer Services', 'Al-baha University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (95, 'Ninon Lawday', 'Account Representative IV', 'Diversified Commercial Services', 'Cogswell Polytechnical College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (96, 'Hetty Fawdrie', 'Operator', 'Air Freight/Delivery Services', 'Dongguk University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (97, 'Cleopatra Layson', 'Web Developer IV', 'Oil & Gas Production', 'Sichuan Fine Art Institute');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (98, 'Edwina Biggs', 'Actuary', 'Food Distributors', 'Wayne State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (99, 'Briney Geffen', 'Registered Nurse', 'n/a', 'Thiagarajar College of Engineering');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (100, 'Karlyn Shaw', 'Office Assistant II', 'Broadcasting', 'Ecole Nationale du Génie de l''Eau et de l''Environnement de Strasbourg');
