delete from trayectoriaentity;
delete from idiomaentity;
delete from HojaDeVidaEntity;
delete from empleadoEntity;
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (25, 'Simeon Alywin', 3.2);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (19, 'Phylis Poluzzi', 3.6);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (59, 'Malorie Jeays', 7.6);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (60, 'Woodman McGee', 1.2);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (76, 'Elly Turrell', 3.5);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (12, 'Dorelia Braksper', 2.4);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (51, 'Clemmie Godsal', 2.8);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (19, 'Vera Smithin', 8.9);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (86, 'Demetris Woodrow', 1.1);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (13, 'Milka Bonevant', 2.5);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (46, 'Elisabet Hrus', 7.0);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (23, 'Virgilio Burdas', 6.5);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (36, 'Giustino Heineking', 8.9);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (15, 'Hillery Beven', 3.0);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (67, 'Justine Binny', 3.4);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (56, 'Linette Balmforth', 4.8);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (8, 'Carlin Jeduch', 10.0);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (31, 'Ingra Danne', 9.5);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (59, 'Tani Kurth', 4.7);
insert into EMPLEADOENTITY (CALIFICACIONPROMEDIO, NAME, TIPO) values (74, 'Bibbye Innes', 7.3);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy', 'Aljouf University', 'Babb Siward', 'Armstrong, Torp and Thiel', 1);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 'Fort Valley State College', 'Baily Schusterl', 'D''Amore Group', 2);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 'Hitec University', 'Dru Worssam', 'Weber Inc', 3);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis', 'Dana College', 'Lydon Mathys', 'Orn and Sons', 4);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', 'Carlos Albizu University', 'Nadya Ibbotson', 'Marks Group', 5);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 'Gardner Webb University', 'Tarrah Wallege', 'Beer-Lakin', 6);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu', 'Kerbala University', 'Brittaney Leuren', 'Wintheiser-Becker', 7);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 'East Carolina University', 'Drusi Peevor', 'Johnston-Herzog', 8);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 'Universidade Federal do Pará', 'Ethelind Burrage', 'Shanahan Inc', 9);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 'Monterey Institute of International Studies', 'Marillin Crockatt', 'O''Hara-Weimann', 10);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', 'Grenoble Ecole de Management', 'Andi Aves', 'Nitzsche, Koss and Hahn', 11);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 'Fachhochschule Kiel', 'Timofei Struan', 'Rolfson-Lakin', 12);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 'University of Urbino', 'Keeley Ianiello', 'Hoppe Group', 13);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 'Warren Wilson College', 'Ardis Manifold', 'Towne Inc', 14);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 'Universität für künstlerische und industrielle Gestaltung Linz', 'Julianne Buckston', 'Ferry-Little', 15);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', 'Sultanah Bahiyah Polytechnic', 'Trude Mallabon', 'Beatty, Davis and Nader', 16);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', 'Universitas Sam Ratulangi', 'Izzy Finkle', 'Adams and Sons', 17);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 'Université Victor Segalen (Bordeaux II)', 'Fernanda Cogley', 'Towne, Pacocha and Smitham', 18);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 'University of Sheffield', 'Ilyse Conyer', 'Becker, Berge and Hudson', 19);
insert into HojaDeVidaEntity (descripcion, formacionacademica, name, perfilprofesional, empleado_id) values ('sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci', 'King Faisal University', 'Shannon Goranov', 'Wilkinson-Mraz', 20);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BA', 'Bosnia and Herzegovina', 'Pale', 1);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CZ', 'Czech Republic', 'Bochov', 2);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Temayang', 3);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Phoenix', 4);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MX', 'Mexico', 'La Libertad', 5);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PT', 'Portugal', 'Almargem do Bispo', 6);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'L�cheng', 7);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Gogosuket', 8);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BR', 'Brazil', 'Tonantins', 9);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Yafan', 10);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PL', 'Poland', 'Lesnica', 11);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MY', 'Malaysia', 'Kuching', 12);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BI', 'Burundi', 'Makamba', 13);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CD', 'Democratic Republic of the Congo', 'Lubao', 14);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Rokoy', 15);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Bangonay', 16);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('TH', 'Thailand', 'Bang Klam', 17);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CA', 'Canada', 'Merritt', 18);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('GB', 'United Kingdom', 'Normanton', 19);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PT', 'Portugal', 'Torre', 20);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PE', 'Peru', 'Tambo', 1);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('AR', 'Argentina', 'Allen', 2);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Dimayon', 3);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CA', 'Canada', 'Metchosin', 4);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Shenzhengqiao', 5);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Echeng', 6);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('VE', 'Venezuela', 'Maracay', 7);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Songculan', 8);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ES', 'Spain', 'Badajoz', 9);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CD', 'Democratic Republic of the Congo', 'Lukolela', 10);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('NL', 'Netherlands', 'Dordrecht', 11);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Jincang', 12);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Simimbaan', 13);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Guanqian', 14);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PS', 'Palestinian Territory', 'Al Buq�ah', 15);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PT', 'Portugal', 'Espinheira', 16);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PL', 'Poland', 'Janikowo', 17);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('RU', 'Russia', 'Vazhiny', 18);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('HN', 'Honduras', 'Valle de �ngeles', 19);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Colorado Springs', 20);

insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Lungaog', 1);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('RU', 'Russia', 'Troitsk', 2);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PE', 'Peru', 'Independencia', 3);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('AR', 'Argentina', 'Embarcaci�n', 4);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BR', 'Brazil', 'Senhor do Bonfim', 5);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CY', 'Cyprus', 'Kiss�nerga', 6);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('FR', 'France', 'Paris 19', 7);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MX', 'Mexico', 'Guadalupe', 8);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('JP', 'Japan', 'Tobetsu', 9);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('HR', 'Croatia', 'Starigrad', 10);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('JP', 'Japan', 'Yukuhashi', 11);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ZW', 'Zimbabwe', 'Dorowa Mining Lease', 12);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('RU', 'Russia', 'Kyra', 13);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('AR', 'Argentina', 'Tamber�as', 14);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Wahai', 15);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Shuangpu', 16);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CZ', 'Czech Republic', 'Zvole', 17);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('GT', 'Guatemala', 'San Antonio Aguas Calientes', 18);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Haguimit', 19);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Jiucaigou', 20);

insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BR', 'Brazil', 'Ilha Solteira', 1);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ET', 'Ethiopia', 'Nejo', 2);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('QA', 'Qatar', 'Al Jumayliyah', 3);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Zhutuo', 4);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PL', 'Poland', 'Miedzybrodzie Bialskie', 5);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('GR', 'Greece', 'Skaramang�s', 6);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BR', 'Brazil', 'Quatro Barras', 7);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PL', 'Poland', 'Syc�w', 8);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Kupahandap', 9);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Huntsville', 10);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Dabaozi', 11);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('FI', 'Finland', 'Tampere', 12);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('SI', 'Slovenia', 'Ribnica na Pohorju', 13);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CI', 'Ivory Coast', 'Bangolo', 14);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Shangjin', 15);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('UY', 'Uruguay', 'San Jos� de Mayo', 16);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PH', 'Philippines', 'Mamali', 17);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MY', 'Malaysia', 'Nusajaya', 18);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Virginia Beach', 19);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PT', 'Portugal', 'Banho e Carvalhosa', 20);

insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('GR', 'Greece', 'Nidri', 1);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Anchorage', 2);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ET', 'Ethiopia', 'Felege Neway', 3);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('TZ', 'Tanzania', 'Kigoma', 4);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Rancaerang', 5);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PT', 'Portugal', 'Al�m do Rio', 6);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('PL', 'Poland', 'Pruszcz Gdanski', 7);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('AS', 'American Samoa', 'Leone', 8);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('US', 'United States', 'Manassas', 9);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('UA', 'Ukraine', 'Zhashkiv', 10);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Huaqiao', 11);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CN', 'China', 'Baqiao', 12);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('CI', 'Ivory Coast', 'Sakassou', 13);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('GH', 'Ghana', 'Kasoa', 14);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('BY', 'Belarus', 'Haradzyeya', 15);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MX', 'Mexico', 'Benito Juarez', 16);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('FR', 'France', 'Boulogne-sur-Mer', 17);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('VN', 'Vietnam', 'Hai Ri�ng', 18);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('ID', 'Indonesia', 'Sugihwaras', 19);
insert into IDIOMAENTITY (ACRONIMO, NAME, REGION, HOJADEVIDA_ID) values ('MA', 'Morocco', 'Kariat Arkmane', 20);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Paroaria gularis', '2001-09-28 21:06:32', '2014-12-01 00:52:20', 'Red-capped cardinal', 1);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Laniaurius atrococcineus', '2001-04-18 02:44:46', '2015-10-01 01:15:56', 'Burchell''s gonolek', 2);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Cercopithecus aethiops', '2005-03-02 04:15:20', '2013-02-04 21:22:23', 'Monkey, vervet', 3);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Eudromia elegans', '2016-12-12 13:31:51', '2016-01-09 05:16:31', 'Elegant crested tinamou', 4);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Tockus erythrorhyncus', '2015-09-10 09:59:11', '1999-11-21 16:40:51', 'Hornbill, red-billed', 5);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Macropus eugenii', '2012-05-31 08:36:37', '2013-02-26 00:24:16', 'Tammar wallaby', 6);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Gyps bengalensis', '2012-11-10 17:52:10', '2010-10-18 01:41:32', 'White-rumped vulture', 7);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Geochelone radiata', '2014-11-23 18:32:58', '2005-08-08 01:41:32', 'Tortoise, radiated', 8);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Sarcorhamphus papa', '2009-03-13 06:00:11', '2003-01-31 01:34:52', 'King vulture', 9);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Lamprotornis nitens', '2005-10-12 06:32:29', '2002-07-23 21:18:37', 'Starling, red-shouldered glossy', 10);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Canis lupus baileyi', '1999-01-22 13:56:17', '2015-10-10 11:09:34', 'Wolf, mexican', 11);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Cacatua tenuirostris', '2014-09-14 20:04:48', '1998-10-29 23:20:53', 'Corella, long-billed', 12);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Cynictis penicillata', '2013-05-27 17:51:43', '2009-06-14 01:51:45', 'Red meerkat', 13);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Dasyurus viverrinus', '2011-06-22 12:18:16', '2005-07-07 21:38:37', 'Native cat', 14);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Equus hemionus', '2000-03-20 16:28:37', '2014-02-13 07:41:13', 'Ass, asiatic wild', 15);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Phoca vitulina', '2000-06-27 19:32:55', '2010-01-16 00:35:26', 'Common seal', 16);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Papio ursinus', '2014-03-15 16:59:32', '2004-10-07 17:30:16', 'Chacma baboon', 17);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Arctogalidia trivirgata', '1999-01-29 07:37:55', '2000-04-08 21:48:32', 'Civet, small-toothed palm', 18);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Myrmecophaga tridactyla', '2011-09-25 15:41:48', '2016-06-05 09:42:29', 'Anteater, giant', 19);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Castor canadensis', '2009-04-26 09:44:39', '1998-09-27 14:08:25', 'North American beaver', 20);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Haliaetus leucogaster', '2016-07-07 04:49:57', '2002-08-15 06:37:01', 'Eagle, white-bellied sea', 1);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Coluber constrictor', '2005-01-28 15:04:18', '1999-02-13 04:29:12', 'Racer snake', 2);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Haliaetus vocifer', '2014-06-28 02:23:52', '2007-09-12 15:25:21', 'Eagle, african fish', 3);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Graspus graspus', '2014-08-06 16:38:22', '2002-01-26 14:21:47', 'Crab, sally lightfoot', 4);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Paroaria gularis', '1999-01-29 15:43:14', '2003-12-16 17:05:01', 'Black-throated cardinal', 5);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Pycnonotus nigricans', '2000-12-21 00:59:37', '2003-12-05 04:42:17', 'African red-eyed bulbul', 6);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Bucorvus leadbeateri', '2009-01-03 18:30:28', '2002-03-02 08:49:01', 'Hornbill, southern ground', 7);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Varanus salvator', '2003-12-28 09:37:17', '2008-11-05 17:41:13', 'Legaan, water', 8);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Eudyptula minor', '2003-04-02 14:25:41', '2001-02-22 14:41:47', 'Penguin, fairy', 9);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Phascogale tapoatafa', '2007-09-28 03:32:09', '2012-04-23 16:49:25', 'Brush-tailed phascogale', 10);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Oxybelis fulgidus', '2001-07-23 23:44:32', '2004-06-04 08:36:30', 'Snake, green vine', 11);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Xerus sp.', '2001-01-06 16:21:29', '2003-05-18 15:42:30', 'African ground squirrel (unidentified)', 12);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Haliaetus leucogaster', '2008-07-10 22:11:50', '2007-03-23 21:11:03', 'White-bellied sea eagle', 13);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Vanellus chilensis', '2007-04-29 22:39:07', '2003-02-08 13:42:28', 'Lapwing, southern', 14);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Pycnonotus nigricans', '2015-08-07 14:47:25', '2006-10-19 18:33:43', 'Bulbul, african red-eyed', 15);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Cyrtodactylus louisiadensis', '2003-01-25 01:33:43', '2012-01-19 17:42:42', 'Gecko, ring-tailed', 16);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Alopochen aegyptiacus', '2003-12-11 02:57:01', '2000-09-18 12:35:58', 'Goose, egyptian', 17);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Philetairus socius', '1999-06-03 07:33:50', '2015-08-06 16:33:36', 'Sociable weaver', 18);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Nyctereutes procyonoides', '2015-08-26 08:17:50', '2001-03-10 07:26:11', 'Raccoon dog', 19);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Anhinga rufa', '2015-07-02 00:33:18', '2008-06-04 19:32:29', 'African darter', 20);

insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Laniaurius atrococcineus', '2001-03-10 10:27:53', '2000-02-28 08:53:28', 'Crimson-breasted shrike', 1);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Rhea americana', '2001-04-09 14:44:54', '2013-12-19 06:01:43', 'Gray rhea', 2);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Zenaida asiatica', '1999-05-03 11:19:03', '2008-10-14 02:19:05', 'Dove, white-winged', 3);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Dicrostonyx groenlandicus', '2014-01-26 07:11:59', '2012-10-26 14:12:45', 'Arctic lemming', 4);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Smithopsis crassicaudata', '2017-05-05 16:22:16', '2012-12-27 21:46:08', 'Dunnart, fat-tailed', 5);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Paroaria gularis', '2014-03-20 08:00:56', '2004-07-27 06:09:36', 'Cardinal, red-capped', 6);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Coluber constrictor', '2004-12-05 04:30:41', '2015-11-30 05:56:24', 'Buttermilk snake', 7);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Mazama gouazoubira', '2016-03-01 13:11:32', '2014-02-08 18:26:19', 'Brocket, brown', 8);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Anas platyrhynchos', '2002-09-23 02:16:42', '2008-11-11 04:26:58', 'Mallard', 9);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Dendrocitta vagabunda', '2005-11-29 21:51:15', '2012-04-18 10:36:02', 'Indian tree pie', 10);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Lamprotornis nitens', '2000-02-16 20:20:30', '2001-08-13 17:29:24', 'Red-shouldered glossy starling', 11);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Columba livia', '2003-11-29 14:48:59', '2009-02-02 10:44:43', 'Feral rock pigeon', 12);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Geochelone elephantopus', '1999-10-15 09:09:18', '2011-12-04 19:06:55', 'Galapagos tortoise', 13);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Macaca radiata', '2014-07-12 07:53:47', '2003-06-06 04:58:24', 'Macaque, bonnet', 14);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Paroaria gularis', '1999-05-07 00:09:01', '2003-03-17 05:30:56', 'Cardinal, black-throated', 15);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Globicephala melas', '2015-08-02 05:19:30', '2005-07-11 15:32:56', 'Whale, long-finned pilot', 16);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Trichoglossus chlorolepidotus', '2007-01-18 06:12:42', '2001-04-13 01:37:36', 'Lorikeet, scaly-breasted', 17);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Tachybaptus ruficollis', '2008-04-09 08:38:43', '2016-10-06 05:58:25', 'Little grebe', 18);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Taurotagus oryx', '2005-07-09 06:35:38', '2001-10-26 13:58:55', 'Eland, common', 19);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Lemur fulvus', '2015-12-06 12:05:10', '2007-10-28 21:55:54', 'Lemur, brown', 20);

insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Eudromia elegans', '2004-04-21 18:01:23', '2001-04-15 05:29:08', 'Tinamou, elegant crested', 1);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Anser anser', '2001-08-17 13:09:44', '2012-09-27 01:01:41', 'Greylag goose', 2);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Dasypus novemcinctus', '2014-11-16 17:00:51', '2008-07-09 05:45:54', 'Armadillo, common long-nosed', 3);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Antidorcas marsupialis', '2013-10-22 00:41:02', '2017-08-12 11:28:27', 'Springbok', 4);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Leptoptilos crumeniferus', '2006-05-04 08:31:40', '2015-01-11 17:54:27', 'Marabou stork', 5);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Smithopsis crassicaudata', '2006-03-03 04:01:43', '2016-07-31 10:50:32', 'Dunnart, fat-tailed', 6);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Bettongia penicillata', '2001-04-26 22:02:17', '2011-01-22 14:16:09', 'Brush-tailed rat kangaroo', 7);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Libellula quadrimaculata', '2016-08-03 16:44:58', '2008-04-07 18:44:07', 'Four-spotted skimmer', 8);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Scolopax minor', '2015-03-10 07:47:37', '2012-10-31 05:15:04', 'American woodcock', 9);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Neotis denhami', '2000-04-03 09:12:09', '2007-06-02 07:03:48', 'Bustard, denham''s', 10);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Bos frontalis', '2014-02-15 08:30:37', '2017-07-22 02:28:24', 'Gaur', 11);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Microcebus murinus', '2017-05-13 17:04:56', '2003-12-12 20:02:38', 'Lemur, grey mouse', 12);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Odocoilenaus virginianus', '2016-05-03 22:46:28', '2015-01-31 20:18:38', 'Deer, white-tailed', 13);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Papio cynocephalus', '2013-12-05 11:17:56', '2011-08-03 01:43:50', 'Baboon, yellow', 14);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Spilogale gracilis', '2011-06-24 21:27:27', '2015-10-23 16:55:55', 'Skunk, western spotted', 15);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Spheniscus mendiculus', '2005-12-08 05:25:30', '2015-03-27 19:51:18', 'Penguin, galapagos', 16);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Paroaria gularis', '2017-07-20 18:16:55', '2007-10-05 18:36:48', 'Cardinal, red-capped', 17);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Heloderma horridum', '2000-02-09 08:24:49', '2011-10-03 08:43:06', 'Monster, gila', 18);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Mycteria leucocephala', '2000-04-17 20:09:18', '2005-12-02 21:36:37', 'Painted stork', 19);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Ctenophorus ornatus', '2011-05-10 05:10:38', '2016-01-18 06:16:41', 'Ornate rock dragon', 20);

insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Casmerodius albus', '2017-05-01 22:49:06', '2003-09-11 15:01:40', 'Great egret', 1);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Castor canadensis', '2014-03-03 15:53:20', '2015-04-25 14:17:37', 'North American beaver', 2);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Ceratotherium simum', '2012-03-22 13:58:05', '2008-10-25 05:55:47', 'Square-lipped rhinoceros', 3);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Varanus salvator', '2007-04-07 19:47:17', '2014-12-27 13:07:24', 'Monitor, two-banded', 4);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Nannopterum harrisi', '2007-10-01 02:15:10', '2013-02-15 18:24:57', 'Flightless cormorant', 5);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Anser caerulescens', '2016-10-20 06:00:18', '2017-04-06 12:31:37', 'Goose, snow', 6);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Sarcophilus harrisii', '2010-01-28 12:22:32', '2011-05-24 23:40:14', 'Devil, tasmanian', 7);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Butorides striatus', '2007-04-09 22:33:51', '2017-08-26 04:57:52', 'Green heron', 8);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Oryx gazella', '2011-10-07 13:46:34', '1998-10-13 02:32:28', 'Gemsbok', 9);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Sitta canadensis', '2017-05-30 09:21:46', '2004-07-04 20:45:55', 'Red-breasted nuthatch', 10);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Dasyurus maculatus', '2009-03-24 02:03:20', '2015-09-28 22:55:30', 'Cat, tiger', 11);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Macropus rufogriseus', '2007-06-18 14:46:03', '2008-05-16 09:48:03', 'Bennett''s wallaby', 12);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Coluber constrictor foxii', '2013-04-16 10:55:54', '2013-02-15 08:01:58', 'Racer, blue', 13);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Phoeniconaias minor', '2007-11-24 18:41:22', '2002-10-04 14:29:14', 'Lesser flamingo', 14);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Pycnonotus barbatus', '2008-11-09 14:15:46', '2016-09-19 07:24:22', 'Black-eyed bulbul', 15);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Chlamydosaurus kingii', '2007-01-10 20:52:43', '2000-07-05 20:17:02', 'Dragon, frilled', 16);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Thylogale stigmatica', '2004-08-10 18:52:16', '2009-06-16 14:24:11', 'Red-legged pademelon', 17);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Sula dactylatra', '2008-11-23 02:12:21', '2008-08-28 11:21:34', 'Masked booby', 18);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Tamiasciurus hudsonicus', '2005-11-12 10:42:09', '1999-07-25 00:48:07', 'Pine squirrel', 19);
insert into Trayectoriaentity (descripcion, fechainicio, fechafin, name, hojadevida_id) values ('Alces alces', '2009-03-07 18:13:55', '2002-01-04 19:54:38', 'Moose', 20);
