delete from TarjetaDeCreditoEntity;
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (1, 'Granville', 'Simonel', 12, 13, 'Collier and Sons', '9/23/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (2, 'Rahal', 'Gong', 12, 12, 'Rempel-Herman', '6/2/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (3, 'Leelah', 'Crayk', 13, 31, 'Marks-Schiller', '4/25/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (4, 'Skelly', 'Bille', 41, 14, 'McLaughlin Group', '6/1/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (5, 'Merridie', 'Tofts', 15, 51, 'Bednar-Watsica', '6/15/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (6, 'Feliza', 'Vollam', 16, 16, 'Kris Inc', '2/8/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (7, 'Janifer', 'Scarth', 17, 16, 'Sauer-Crona', '8/11/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (8, 'Abran', 'Sandhill', 18, 8, 'Dach-Lind', '4/9/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (9, 'Batsheva', 'Knibbs', 29, 9, 'Block, Bailey and Harber', '2/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (10, 'Gerda', 'Cotterel', 10, 10, 'Klocko, Labadie and Schultz', '10/21/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (11, 'Miguel', 'Trousdale', 11, 11, 'Kiehn-Bernhard', '3/2/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (12, 'Helene', 'Fidilis', 12, 12, 'Runolfsdottir Group', '8/14/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (13, 'Dorotea', 'Pleavin', 13, 13, 'Kerluke Group', '6/16/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (14, 'Kenny', 'Bielfeldt', 14, 14, 'Huel-Goyette', '12/25/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (15, 'Stacey', 'Bullocke', 15, 15, 'Turcotte and Sons', '2/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (16, 'Geno', 'McCart', 16, 16, 'Wunsch LLC', '4/28/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (17, 'Nappie', 'Aspall', 17, 17, 'Ritchie, Ernser and O''Keefe', '9/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (18, 'Berni', 'Linzey', 18, 18, 'Stracke-Senger', '10/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (19, 'Patric', 'Dyer', 19, 19, 'Steuber, Crooks and Funk', '5/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (20, 'Caitrin', 'Shaudfurth', 20, 20, 'Bins-Carroll', '10/4/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (21, 'Raoul', 'Courtonne', 21, 21, 'Kertzmann, Bernier and Renner', '10/24/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (22, 'Thoma', 'Haestier', 22, 22, 'VonRueden-Boehm', '3/18/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (23, 'Britt', 'Osmant', 23, 23, 'Lowe-Christiansen', '1/5/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (24, 'Spenser', 'Colvill', 24, 24, 'Langworth and Sons', '11/21/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (25, 'Evangelina', 'Hadgraft', 25, 25, 'Mayert, Batz and Hand', '4/1/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (26, 'Maddalena', 'Gibbins', 26, 26, 'Conroy, Barton and Pollich', '6/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (27, 'Luther', 'Pert', 27, 27, 'Little-Bauch', '9/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (28, 'Henrieta', 'Cumo', 28, 28, 'Mayer and Sons', '6/19/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (29, 'Cathleen', 'Marzella', 29, 29, 'Hoeger Group', '7/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (30, 'Jonathon', 'Stops', 30, 30, 'Boyle, O''Hara and Buckridge', '8/22/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (31, 'Willa', 'Parlott', 31, 31, 'O''Reilly, Towne and McGlynn', '9/8/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (32, 'Alica', 'Kubicka', 32, 32, 'Batz-Schroeder', '7/27/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (33, 'Cesaro', 'Tivers', 33, 33, 'Schulist LLC', '12/2/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (34, 'Flem', 'Trimble', 34, 34, 'Ratke-Blanda', '9/20/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (35, 'Hadria', 'Hammerberg', 35, 35, 'Rempel, Harvey and Rice', '10/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (36, 'Nolan', 'Foale', 36, 36, 'Schultz, Bruen and Parisian', '6/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (37, 'Vina', 'Kenworthey', 37, 37, 'Williamson, Corkery and Daniel', '8/25/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (38, 'La verne', 'Leachman', 38, 38, 'Denesik-Gleason', '7/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (39, 'Doralin', 'Stove', 39, 39, 'Kuhn and Sons', '1/3/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (40, 'Link', 'Pickerin', 40, 40, 'Bosco-Connelly', '12/18/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (41, 'Rea', 'Sheldrick', 41, 41, 'Schmidt, Lockman and Schmidt', '5/12/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (42, 'Ludwig', 'Tolman', 42, 42, 'McKenzie-Mraz', '6/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (43, 'Francoise', 'Albin', 43, 43, 'Crooks-Ward', '3/29/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (44, 'Sheilakathryn', 'Guerrieri', 44, 44, 'Marvin, Swift and Wolff', '12/11/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (45, 'Amelita', 'Matushevich', 45, 45, 'McKenzie and Sons', '7/18/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (46, 'Kassi', 'Cail', 46, 46, 'Marks-Wunsch', '11/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (47, 'Elberta', 'Rushman', 47, 47, 'Kunze-Moore', '8/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (48, 'Kirsten', 'Chaimson', 48, 48, 'Klein-Schneider', '1/20/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (49, 'Douglass', 'Hartley', 49, 49, 'Predovic-Rippin', '4/24/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (50, 'Ronnie', 'Auston', 50, 50, 'Pollich-O''Kon', '10/15/2016');