delete from trayectoriaentity;
delete from HojaDeVidaEntity;
delete from EMPLEADOENTITY;
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (50, 'Felic Prate', 'Librarian', 'Integrated oil Companies', 'Universidade de Aveiro');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (51, 'Karla Winspear', 'VP Quality Control', 'Other Specialty Stores', 'University of East Srarajevo');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (52, 'Jack Mumbray', 'Senior Financial Analyst', 'n/a', 'Instituto Politécnico do Cávado e do Ave');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (53, 'Trina Bridgstock', 'Health Coach II', 'Real Estate', 'Elizabethtown College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (54, 'Bunnie Campana', 'Environmental Tech', 'Forest Products', 'Universidad Autónoma Metropolitana - Azcapotzalco');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (55, 'Misty Liveing', 'Chief Design Engineer', 'Commercial Banks', 'Adventist University of Africa');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (56, 'Tremain Bish', 'Programmer Analyst IV', 'Medical/Dental Instruments', 'St. Lawrence University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (57, 'Gael Welfair', 'Paralegal', 'Television Services', 'Tashkent Pharmaceutical Institute');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (58, 'Coralyn Slowgrove', 'Developer III', 'Hotels/Resorts', 'Ouachita Baptist University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (59, 'Annnora Clere', 'Food Chemist', 'Broadcasting', 'Botswana International University of Science & Technology');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (60, 'Herrick Beininck', 'Safety Technician IV', 'Metal Fabrications', 'Institute of Industrial Electronics Engineering');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (61, 'Anabelle Scoyles', 'VP Product Management', 'n/a', 'LICCSAL Business College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (62, 'Coretta Fairebrother', 'Web Developer IV', 'Major Banks', 'South Asian University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (63, 'Auria Pittway', 'Mechanical Systems Engineer', 'Major Chemicals', 'Maharishi Dayanand University, Rohtak (Haryana )');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (64, 'Karen Nosworthy', 'Software Consultant', 'Catalog/Specialty Distribution', 'Rose-Hulman Institute of Technology');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (65, 'Cristie Heiden', 'Nuclear Power Engineer', 'Television Services', 'University of Texas at Dallas');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (66, 'Germaine Carlyle', 'Desktop Support Technician', 'Containers/Packaging', 'Kalmyk State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (67, 'Annadiana Selbach', 'Staff Scientist', 'Power Generation', 'Universidad de San Carlos de Guatemala');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (68, 'Gerrard Stanley', 'Developer II', 'Containers/Packaging', 'Khabarovsk State Academy of Economics and Law');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (69, 'Sabina Simonelli', 'VP Quality Control', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', 'Illinois State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (70, 'Gilbertine Stubbings', 'General Manager', 'Military/Government/Technical', 'Université des Sciences et Technologies de Lille (Lille I)');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (71, 'Armstrong Fishpoole', 'Nurse', 'Marine Transportation', 'Indian Institute of Technology, Guwahati');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (72, 'Merle Stenett', 'Structural Engineer', 'Industrial Machinery/Components', 'Katholische Universität Eichstätt');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (73, 'Othilie Cammacke', 'Assistant Media Planner', 'n/a', 'Medical University of South Carolina');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (74, 'Law Diess', 'Teacher', 'Specialty Chemicals', 'Kokugakuin University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (75, 'Alonzo Shynn', 'Structural Analysis Engineer', 'Computer Software: Prepackaged Software', 'Institute of Teachers Education, Tengku Ampuan Afzan');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (76, 'Gerardo Maxwaile', 'Software Consultant', 'Major Chemicals', 'Norton University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (77, 'Francisco Varga', 'Help Desk Operator', 'Air Freight/Delivery Services', 'Universidade Catolica Portuguesa');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (78, 'Dacia Mapes', 'Project Manager', 'Diversified Commercial Services', 'Aristotle University of Thessaloniki');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (79, 'Myrwyn Reneke', 'Structural Analysis Engineer', 'Packaged Foods', 'Joetsu University of Education');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (80, 'Georgette Camm', 'Media Manager II', 'Real Estate', 'Dominica State College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (81, 'Rochelle Caccavari', 'Associate Professor', 'n/a', 'Debre Birhan University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (82, 'Darby Bunker', 'Senior Cost Accountant', 'Property-Casualty Insurers', 'Pitzer College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (83, 'Fred Behrend', 'Project Manager', 'Major Banks', 'Hogeschool van Amsterdam');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (84, 'Pia Presho', 'Desktop Support Technician', 'Oilfield Services/Equipment', 'University of Cape Town');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (85, 'Elianora Vickers', 'Human Resources Manager', 'n/a', 'Pontificio Ateneo Antonianum');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (86, 'Jessika Wendover', 'Quality Engineer', 'Electric Utilities: Central', 'City University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (87, 'Revkah Mityushin', 'Help Desk Operator', 'Homebuilding', 'Siberian State Industrial University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (88, 'Farrel Hatry', 'Actuary', 'Investment Bankers/Brokers/Service', 'Wake Forest University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (89, 'Hillery Lagneaux', 'Software Engineer II', 'Oil & Gas Production', 'Marij State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (90, 'Simone Bygott', 'Data Coordiator', 'Major Banks', 'Emmaus Bible College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (91, 'Moreen Garralts', 'Community Outreach Specialist', 'Savings Institutions', 'Maseno University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (92, 'Mick Maltman', 'Operator', 'n/a', 'Menlo College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (93, 'Mariana Bignold', 'Marketing Manager', 'Major Pharmaceuticals', 'Muskingum College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (94, 'Emmit Filipczynski', 'Senior Quality Engineer', 'Finance: Consumer Services', 'Al-baha University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (95, 'Ninon Lawday', 'Account Representative IV', 'Diversified Commercial Services', 'Cogswell Polytechnical College');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (96, 'Hetty Fawdrie', 'Operator', 'Air Freight/Delivery Services', 'Dongguk University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (97, 'Cleopatra Layson', 'Web Developer IV', 'Oil & Gas Production', 'Sichuan Fine Art Institute');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (98, 'Edwina Biggs', 'Actuary', 'Food Distributors', 'Wayne State University');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (99, 'Briney Geffen', 'Registered Nurse', 'n/a', 'Thiagarajar College of Engineering');
insert into HojaDeVidaEntity (id, name, descripcion, perfilProfesional, formacionAcademica) values (100, 'Karlyn Shaw', 'Office Assistant II', 'Broadcasting', 'Ecole Nationale du Génie de l''Eau et de l''Environnement de Strasbourg');

insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (50, 'Platalea leucordia', '2017-03-12 18:35:32', '2016-11-01 14:50:27', 'White spoonbill', 50);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (51, 'Lamprotornis chalybaeus', '2017-06-26 10:57:21', '2017-09-16 01:15:50', 'Greater blue-eared starling', 51);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (52, 'Cracticus nigroagularis', '2017-07-09 14:10:23', '2016-12-17 23:26:06', 'Bird, black-throated butcher', 52);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (53, 'Cereopsis novaehollandiae', '2017-01-17 02:30:23', '2016-12-20 05:25:39', 'Cape Barren goose', 53);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (54, 'Antilope cervicapra', '2017-08-15 01:11:43', '2017-07-13 08:15:52', 'Blackbuck', 54);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (55, 'Pycnonotus barbatus', '2017-07-06 12:01:55', '2017-02-23 18:08:10', 'Black-eyed bulbul', 55);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (56, 'Macaca radiata', '2016-11-13 16:08:04', '2016-11-30 11:47:15', 'Macaque, bonnet', 56);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (57, 'Sarcophilus harrisii', '2017-03-03 06:32:51', '2017-04-10 18:13:10', 'Tasmanian devil', 57);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (58, 'Alopex lagopus', '2016-10-02 07:30:08', '2017-09-02 15:33:38', 'Arctic fox', 58);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (59, 'Grus canadensis', '2016-11-13 14:57:53', '2016-12-14 13:26:41', 'Sandhill crane', 59);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (60, 'Myrmecophaga tridactyla', '2017-09-20 00:56:49', '2016-12-08 17:45:44', 'Giant anteater', 60);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (61, 'Ara chloroptera', '2017-04-27 10:28:28', '2017-09-10 07:45:05', 'Macaw, red and blue', 61);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (62, 'Tringa glareola', '2016-10-26 05:40:49', '2017-07-10 03:52:33', 'Sandpiper, spotted wood', 62);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (63, 'Arctogalidia trivirgata', '2017-09-18 05:25:54', '2017-01-15 23:22:06', 'Small-toothed palm civet', 63);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (64, 'Ursus maritimus', '2017-02-24 09:13:26', '2016-10-18 19:31:55', 'Polar bear', 64);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (65, 'Sciurus niger', '2017-09-04 03:36:33', '2017-06-27 16:27:12', 'Squirrel, eastern fox', 65);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (66, 'Vanellus chilensis', '2017-05-08 12:59:38', '2017-09-02 06:41:30', 'Lapwing, southern', 66);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (67, 'Streptopelia decipiens', '2016-12-28 00:53:10', '2017-04-22 00:40:16', 'Mourning collared dove', 67);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (68, 'Sceloporus magister', '2017-06-05 21:47:49', '2016-10-02 07:29:37', 'Desert spiny lizard', 68);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (69, 'Tragelaphus angasi', '2017-05-13 17:04:29', '2017-03-11 04:43:10', 'Nyala', 69);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (70, 'Pelecans onocratalus', '2017-07-19 16:23:58', '2017-01-20 19:54:01', 'Great white pelican', 70);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (71, 'Tiliqua scincoides', '2017-02-28 05:19:10', '2017-03-11 23:56:39', 'Blue-tongued lizard', 71);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (72, 'Ovis canadensis', '2017-04-17 17:37:09', '2017-02-07 03:52:31', 'American bighorn sheep', 72);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (73, 'Varanus salvator', '2016-09-28 11:21:33', '2016-11-10 12:42:44', 'Monitor, two-banded', 73);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (74, 'Ninox superciliaris', '2017-07-13 11:29:37', '2017-09-05 14:25:50', 'Owl, madagascar hawk', 74);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (75, 'Lorythaixoides concolor', '2017-01-26 05:31:39', '2016-11-16 11:53:34', 'Lourie, grey', 75);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (76, 'Nucifraga columbiana', '2016-10-17 17:46:02', '2016-11-13 05:22:43', 'Clark''s nutcracker', 76);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (77, 'Meles meles', '2017-03-13 15:38:33', '2016-11-02 00:03:22', 'Badger, european', 77);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (78, 'Ardea golieth', '2017-08-19 20:24:35', '2016-10-03 23:55:02', 'Heron, goliath', 78);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (79, 'Limnocorax flavirostra', '2016-09-26 21:06:21', '2017-08-06 20:17:17', 'African black crake', 79);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (80, 'Coracias caudata', '2016-10-31 06:45:47', '2017-03-27 19:40:47', 'Roller, lilac-breasted', 80);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (81, 'Alouatta seniculus', '2017-08-21 15:28:37', '2017-07-30 04:06:20', 'Red howler monkey', 81);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (82, 'Gyps bengalensis', '2017-06-16 21:44:26', '2017-02-22 19:23:31', 'Oriental white-backed vulture', 82);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (83, 'Thalasseus maximus', '2016-11-02 03:58:45', '2017-08-16 04:29:39', 'Tern, royal', 83);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (84, 'Junonia genoveua', '2017-09-02 20:36:00', '2017-07-23 20:10:40', 'Tropical buckeye butterfly', 84);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (85, 'Anser caerulescens', '2017-02-17 18:37:24', '2017-03-09 22:28:49', 'Snow goose', 85);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (86, 'Macropus rufogriseus', '2016-10-07 16:35:57', '2017-03-31 05:27:23', 'Wallaby, bennett''s', 86);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (87, 'Dasypus septemcincus', '2017-09-11 11:30:51', '2017-03-12 04:34:42', 'Seven-banded armadillo', 87);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (88, 'Anthropoides paradisea', '2016-09-25 06:58:51', '2017-06-17 01:19:14', 'Crane, stanley', 88);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (89, 'Lamprotornis superbus', '2017-07-24 12:48:05', '2016-10-26 16:10:43', 'Superb starling', 89);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (90, 'Zonotrichia capensis', '2017-04-11 03:43:00', '2017-02-15 04:52:52', 'Sparrow, rufous-collared', 90);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (91, 'Theropithecus gelada', '2016-11-03 13:58:40', '2017-03-11 09:54:52', 'Bleeding heart monkey', 91);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (92, 'Procyon lotor', '2017-06-14 23:21:00', '2016-09-26 23:57:18', 'Raccoon, common', 92);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (93, 'Iguana iguana', '2017-07-21 02:12:36', '2017-07-25 09:08:56', 'Iguana, common green', 93);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (94, 'Phoenicopterus chilensis', '2017-04-08 08:01:32', '2017-05-25 07:02:17', 'Flamingo, chilean', 94);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (95, 'Salvadora hexalepis', '2017-04-05 02:37:46', '2017-04-13 00:25:18', 'Snake, western patch-nosed', 95);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (96, 'Orcinus orca', '2016-09-28 03:15:16', '2017-04-14 06:39:42', 'Orca', 96);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (97, 'Varanus sp.', '2017-03-30 16:07:20', '2017-08-23 16:53:06', 'Legaan, Monitor (unidentified)', 97);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (98, 'Alligator mississippiensis', '2017-07-10 18:09:18', '2016-10-15 19:56:28', 'American alligator', 98);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (99, 'Ovis ammon', '2017-04-29 00:57:36', '2017-08-25 03:58:00', 'Sheep, red', 99);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (100, 'Francolinus coqui', '2017-07-30 01:55:57', '2017-09-11 22:56:00', 'Francolin, coqui', 100);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (101, 'Anhinga rufa', '2017-09-02 19:36:03', '2016-12-05 00:45:47', 'Darter, african', 50);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (102, 'Larus dominicanus', '2017-03-07 22:44:43', '2017-05-05 06:03:43', 'Gull, kelp', 51);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (103, 'Francolinus swainsonii', '2017-04-03 15:11:49', '2017-02-17 19:30:43', 'Francolin, swainson''s', 52);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (104, 'Phaethon aethereus', '2016-12-10 09:27:05', '2017-04-30 06:43:25', 'Bird, red-billed tropic', 53);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (105, 'Buteo regalis', '2016-11-26 14:27:51', '2017-04-11 06:12:41', 'Ferruginous hawk', 54);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (106, 'Ursus americanus', '2016-09-21 02:43:19', '2017-06-23 20:41:00', 'Bear, black', 55);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (107, 'Eumetopias jubatus', '2017-04-26 17:48:58', '2016-11-04 04:12:24', 'Lion, steller''s sea', 56);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (108, 'Alligator mississippiensis', '2017-09-20 12:56:00', '2017-04-27 20:43:33', 'Alligator, mississippi', 57);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (109, 'Diceros bicornis', '2017-01-04 07:16:18', '2017-05-17 04:26:12', 'Rhinoceros, black', 58);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (110, 'Pterocles gutturalis', '2016-10-04 05:48:23', '2016-11-02 23:08:25', 'Yellow-throated sandgrouse', 59);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (111, 'Ammospermophilus nelsoni', '2017-01-21 12:06:23', '2017-07-01 06:27:10', 'Antelope ground squirrel', 60);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (112, 'Ursus americanus', '2017-06-23 13:24:21', '2017-03-22 18:31:38', 'Bear, american black', 61);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (113, 'Tachyglossus aculeatus', '2016-12-09 21:58:08', '2017-01-03 23:16:40', 'Anteater, australian spiny', 62);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (114, 'Phylurus milli', '2017-02-02 00:23:40', '2017-05-26 10:24:34', 'Barking gecko', 63);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (115, 'Sarkidornis melanotos', '2017-05-04 03:02:06', '2017-04-19 20:13:30', 'Goose, knob-nosed', 64);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (116, 'Hystrix cristata', '2017-02-04 02:11:09', '2017-05-16 23:34:42', 'African porcupine', 65);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (117, 'Marmota monax', '2016-11-23 15:11:10', '2016-09-22 21:49:38', 'Woodchuck', 66);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (118, 'Canis lupus', '2017-07-06 13:38:28', '2016-11-25 16:05:35', 'Wolf, common', 67);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (119, 'Loxodonta africana', '2016-12-24 17:31:39', '2016-11-15 23:38:35', 'Elephant, african', 68);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (120, 'Hippotragus equinus', '2016-12-18 21:18:04', '2017-08-20 13:59:56', 'Roan antelope', 69);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (121, 'Alcelaphus buselaphus cokii', '2016-10-23 11:28:34', '2017-04-23 02:15:18', 'Hartebeest, coke''s', 70);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (122, 'Marmota monax', '2017-01-04 09:07:30', '2017-04-26 13:04:49', 'Woodchuck', 71);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (123, 'Butorides striatus', '2017-06-25 22:19:27', '2017-02-07 02:22:17', 'Heron, little', 72);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (124, 'Rhabdomys pumilio', '2017-08-22 10:23:03', '2017-05-08 10:41:21', 'Mouse, four-striped grass', 73);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (125, 'Pteropus rufus', '2017-08-07 13:44:18', '2017-08-19 15:08:30', 'Madagascar fruit bat', 74);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (126, 'Pteronura brasiliensis', '2017-04-13 01:35:35', '2017-04-27 23:13:18', 'Otter, brazilian', 75);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (127, 'Eurocephalus anguitimens', '2016-12-03 21:44:47', '2017-07-29 08:11:43', 'Shrike, southern white-crowned', 76);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (128, 'Casmerodius albus', '2017-03-30 02:06:50', '2017-07-11 19:27:31', 'Great egret', 77);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (129, 'Mazama gouazoubira', '2017-02-27 12:11:11', '2017-05-25 17:41:59', 'Brocket, brown', 78);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (130, 'Ephippiorhynchus mycteria', '2017-09-13 20:31:18', '2017-08-31 00:29:55', 'Stork, black-necked', 79);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (131, 'unavailable', '2017-05-29 03:08:06', '2017-03-26 07:53:47', 'Snake (unidentified)', 80);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (132, 'Choloepus hoffmani', '2017-08-01 13:08:39', '2017-01-09 23:37:05', 'Sloth, two-toed tree', 81);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (133, 'Cathartes aura', '2017-03-05 19:21:14', '2016-12-07 22:56:09', 'Turkey vulture', 82);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (134, 'Cervus canadensis', '2017-07-01 08:00:38', '2017-02-23 01:55:09', 'Elk, Wapiti', 83);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (135, 'Butorides striatus', '2017-09-01 19:53:22', '2017-07-12 15:03:41', 'Green heron', 84);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (136, 'unavailable', '2017-09-17 02:20:57', '2017-03-29 01:30:32', 'Butterfly (unidentified)', 85);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (137, 'Amblyrhynchus cristatus', '2016-11-06 00:13:15', '2016-11-08 14:42:55', 'Iguana, marine', 86);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (138, 'Spermophilus tridecemlineatus', '2017-07-09 19:55:53', '2017-02-05 14:21:34', 'Thirteen-lined squirrel', 87);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (139, 'Phoeniconaias minor', '2016-11-14 12:09:45', '2016-11-02 10:44:01', 'Flamingo, lesser', 88);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (140, 'Pelecanus occidentalis', '2017-03-22 09:20:05', '2016-11-02 22:49:02', 'Pelican, brown', 89);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (141, 'Lutra canadensis', '2017-01-25 20:49:20', '2017-05-06 12:51:18', 'Otter, north american river', 90);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (142, 'Pseudalopex gymnocercus', '2016-11-05 13:45:28', '2017-08-23 19:06:43', 'Fox, pampa gray', 91);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (143, 'Choloepus hoffmani', '2016-10-16 02:26:15', '2016-12-19 18:47:25', 'Hoffman''s sloth', 92);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (144, 'Coendou prehensilis', '2016-11-27 15:32:02', '2017-04-27 21:27:20', 'Tree porcupine', 93);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (145, 'unavailable', '2017-02-24 12:40:38', '2016-12-13 09:47:28', 'Cormorant (unidentified)', 94);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (146, 'Climacteris melanura', '2017-07-16 15:48:16', '2017-02-22 16:12:48', 'Black-tailed tree creeper', 95);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (147, 'Felis pardalis', '2017-07-07 14:49:50', '2017-07-28 23:23:56', 'Ocelot', 96);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (148, 'Antechinus flavipes', '2017-08-22 21:22:12', '2017-03-24 20:58:07', 'Brown antechinus', 97);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (149, 'Thylogale stigmatica', '2017-08-28 19:08:44', '2017-08-25 06:24:50', 'Pademelon, red-legged', 98);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (150, 'Ardea cinerea', '2017-02-06 13:14:10', '2017-02-21 19:44:21', 'Gray heron', 99);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (151, 'Delphinus delphis', '2017-04-06 12:32:46', '2017-03-08 21:37:10', 'Common dolphin', 100);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (152, 'Sarcorhamphus papa', '2017-05-30 06:26:09', '2017-03-22 15:56:07', 'King vulture', 51);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (153, 'Phalacrocorax niger', '2017-03-28 05:28:00', '2017-05-07 10:05:02', 'Cormorant, javanese', 52);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (154, 'Kobus vardonii vardoni', '2017-03-26 12:57:54', '2017-04-16 09:14:46', 'Puku', 53);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (155, 'Melanerpes erythrocephalus', '2017-05-20 12:35:00', '2016-11-29 11:12:54', 'Woodpecker, red-headed', 54);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (156, 'Laniaurius atrococcineus', '2016-09-30 18:39:00', '2016-12-13 21:35:55', 'Crimson-breasted shrike', 55);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (157, 'Macropus rufogriseus', '2016-12-15 06:02:28', '2017-04-11 20:19:38', 'Wallaby, bennett''s', 56);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (158, 'Acrobates pygmaeus', '2017-06-10 05:30:42', '2017-08-01 08:12:40', 'Pygmy possum', 57);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (159, 'Uraeginthus granatina', '2017-06-06 15:04:30', '2016-11-02 06:14:42', 'Grenadier, common', 58);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (160, 'Dicrostonyx groenlandicus', '2017-01-10 16:29:29', '2017-04-06 16:44:51', 'Arctic lemming', 59);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (161, 'Hippopotamus amphibius', '2016-11-09 16:53:36', '2017-07-06 07:36:16', 'Hippopotamus', 60);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (162, 'Sciurus vulgaris', '2016-11-28 00:58:44', '2016-10-15 12:33:12', 'Squirrel, european red', 61);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (163, 'Porphyrio porphyrio', '2017-03-20 18:51:07', '2016-12-10 19:08:43', 'Purple moorhen', 62);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (164, 'Funambulus pennati', '2017-05-11 09:12:34', '2016-10-11 18:09:33', 'Palm squirrel', 63);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (165, 'Nycticorax nycticorax', '2017-04-03 00:20:06', '2017-04-24 11:15:32', 'Black-crowned night heron', 64);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (166, 'Papio ursinus', '2017-01-30 14:57:38', '2016-10-27 03:11:34', 'Chacma baboon', 65);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (167, 'Spheniscus magellanicus', '2016-12-10 18:17:16', '2017-03-25 20:57:12', 'Magellanic penguin', 66);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (168, 'Ovis ammon', '2017-01-23 01:48:25', '2017-02-15 20:13:18', 'Red sheep', 67);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (169, 'Lemur fulvus', '2017-03-07 07:42:12', '2016-11-06 04:45:44', 'Lemur, brown', 68);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (170, 'Diceros bicornis', '2017-06-28 19:40:58', '2016-12-08 10:39:08', 'Rhinoceros, black', 69);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (171, 'Semnopithecus entellus', '2017-03-02 01:52:41', '2017-01-19 03:09:50', 'Langur, hanuman', 70);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (172, 'Ephipplorhynchus senegalensis', '2017-08-26 16:32:15', '2017-08-08 02:28:37', 'Stork, saddle-billed', 71);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (173, 'Dicrurus adsimilis', '2017-01-17 02:27:21', '2017-04-18 17:51:08', 'Drongo, fork-tailed', 72);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (174, 'Ursus maritimus', '2017-04-05 05:29:06', '2016-09-27 18:02:35', 'Polar bear', 73);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (175, 'Felis wiedi or Leopardus weidi', '2017-04-05 13:19:18', '2017-07-12 10:32:29', 'Cat, long-tailed spotted', 74);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (176, 'Melophus lathami', '2017-03-16 20:29:53', '2017-07-06 23:28:18', 'Crested bunting', 75);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (177, 'Coracias caudata', '2017-04-28 21:34:32', '2016-12-18 00:10:52', 'Lilac-breasted roller', 76);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (178, 'Microcebus murinus', '2017-08-15 15:40:58', '2016-10-24 23:26:38', 'Lemur, lesser mouse', 77);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (179, 'Parus atricapillus', '2017-03-21 10:02:10', '2017-08-13 14:29:22', 'Black-capped chickadee', 78);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (180, 'Snycerus caffer', '2017-03-15 03:55:48', '2017-01-26 04:11:53', 'Buffalo, african', 79);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (181, 'Diomedea irrorata', '2017-07-08 21:24:05', '2017-09-04 06:57:56', 'Waved albatross', 80);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (182, 'Diomedea irrorata', '2017-03-14 22:21:29', '2016-11-26 01:01:05', 'Albatross, galapagos', 81);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (183, 'Spheniscus magellanicus', '2016-10-11 18:15:10', '2017-06-18 12:05:33', 'Magellanic penguin', 82);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (184, 'Vanellus chilensis', '2016-12-08 02:55:46', '2017-04-09 10:15:54', 'Lapwing, southern', 83);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (185, 'Iguana iguana', '2016-10-15 15:11:49', '2017-05-19 01:21:51', 'Common green iguana', 84);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (186, 'Lemur catta', '2016-10-01 23:31:33', '2017-02-21 19:45:07', 'Ring-tailed lemur', 85);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (187, 'Macropus eugenii', '2016-12-20 21:17:36', '2017-05-15 01:29:39', 'Wallaby, tammar', 86);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (188, 'Felis wiedi or Leopardus weidi', '2017-08-31 09:15:17', '2017-01-26 03:18:11', 'Long-tailed spotted cat', 87);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (189, 'Megaderma spasma', '2016-12-16 07:36:31', '2017-04-05 21:25:18', 'Bat, asian false vampire', 88);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (190, 'Bucephala clangula', '2017-06-10 13:53:18', '2017-08-12 16:58:11', 'Barrows goldeneye', 89);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (191, 'Macropus robustus', '2017-09-11 10:45:19', '2017-08-05 00:33:01', 'Wallaby, euro', 90);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (192, 'Trachyphonus vaillantii', '2017-06-14 00:15:58', '2016-10-22 14:38:25', 'Barbet, levaillant''s', 91);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (193, 'Vombatus ursinus', '2016-10-31 00:09:42', '2017-04-23 02:20:56', 'Wombat, common', 92);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (194, 'Spermophilus richardsonii', '2017-01-31 10:33:17', '2017-08-03 09:18:06', 'Richardson''s ground squirrel', 93);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (195, 'Mungos mungo', '2017-08-08 12:40:59', '2016-12-16 09:15:45', 'Mongoose, banded', 94);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (196, 'Canis lupus lycaon', '2016-12-17 16:15:57', '2016-09-24 21:59:21', 'Timber wolf', 95);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (197, 'Caiman crocodilus', '2017-08-12 18:24:56', '2016-11-11 22:10:03', 'Caiman, spectacled', 96);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (198, 'Uraeginthus granatina', '2017-01-23 21:22:43', '2017-03-02 04:20:59', 'Purple grenadier', 97);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (199, 'Oryx gazella', '2017-02-25 07:53:01', '2017-03-06 03:26:07', 'Gemsbok', 98);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (200, 'Hyaena brunnea', '2017-02-08 10:45:54', '2017-09-05 17:36:44', 'Hyena, brown', 99);
insert into trayectoriaentity (id, descripcion, fechainicio, fechafin, name, hojadevida_id) values (201, 'Psittacula krameri', '2017-09-19 20:44:47', '2017-01-18 16:07:26', 'Parakeet, rose-ringed', 100);
delete from AREADECONOCIMIENTOENTITY;
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('convallis tortor', 'Human Resources', 80);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('fusce', 'Human Resources', 81);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('ante', 'Engineering', 82);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('augue', 'Human Resources', 83);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('mattis odio', 'Support', 84);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('velit vivamus', 'Business Development', 85);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('faucibus', 'Engineering', 86);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('velit eu', 'Human Resources', 87);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('dapibus', 'Marketing', 88);
insert into AREADECONOCIMIENTOENTITY (name, descripcion, id) values ('sit amet', 'Accounting', 89);
delete from CalificacionEntity;
insert into CalificacionEntity (id, name, comentario, calificacion) values (50, 'Damian', 'Turpis.mp3', 84.5);
insert into CalificacionEntity (id, name, comentario, calificacion) values (51, 'Omar', 'UltricesVelAugue.avi', 10.5);
insert into CalificacionEntity (id, name, comentario, calificacion) values (52, 'Camel', 'Sodales.gif', 70.5);
insert into CalificacionEntity (id, name, comentario, calificacion) values (53, 'Monte', 'Id.ppt', 35.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (54, 'Lebbie', 'AmetNullaQuisque.ppt', 23.9);
insert into CalificacionEntity (id, name, comentario, calificacion) values (55, 'Arri', 'InConsequatUt.ppt', 80.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (56, 'Krysta', 'RidiculusMusVivamus.ppt', 26.3);
insert into CalificacionEntity (id, name, comentario, calificacion) values (57, 'Amandi', 'QuamPede.ppt', 62.5);
insert into CalificacionEntity (id, name, comentario, calificacion) values (58, 'Sara-ann', 'EgetElitSodales.xls', 1.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (59, 'Wallache', 'EratIdMauris.ppt', 47.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (60, 'Deedee', 'PotentiNullamPorttitor.mov', 23.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (61, 'Lauren', 'Aliquet.mp3', 80.2);
insert into CalificacionEntity (id, name, comentario, calificacion) values (62, 'Nerissa', 'Praesent.ppt', 39.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (63, 'Wain', 'ViverraPede.xls', 36.4);
insert into CalificacionEntity (id, name, comentario, calificacion) values (64, 'Dagny', 'ConsectetuerAdipiscing.tiff', 20.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (65, 'Ealasaid', 'SitAmetLobortis.avi', 61.3);
insert into CalificacionEntity (id, name, comentario, calificacion) values (66, 'Archibald', 'AeneanAuctorGravida.jpeg', 59.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (67, 'Madelaine', 'IaculisJusto.doc', 81.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (68, 'Dody', 'UltricesVelAugue.pdf', 87.3);
insert into CalificacionEntity (id, name, comentario, calificacion) values (69, 'Jsandye', 'MorbiOdio.mp3', 76.1);
insert into CalificacionEntity (id, name, comentario, calificacion) values (70, 'Lizzie', 'NullamSit.mp3', 92.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (71, 'Raviv', 'AtVelitEu.mp3', 49.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (72, 'Edwin', 'In.pdf', 91.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (73, 'Avigdor', 'VestibulumVelit.jpeg', 71.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (74, 'Cornelius', 'IdLigula.avi', 64.9);
insert into CalificacionEntity (id, name, comentario, calificacion) values (75, 'Yard', 'JustoMaecenas.avi', 81.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (76, 'Coretta', 'NislVenenatisLacinia.xls', 71.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (77, 'Caron', 'UltricesPosuereCubilia.mpeg', 49.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (78, 'Nilson', 'IntegerANibh.jpeg', 10.1);
insert into CalificacionEntity (id, name, comentario, calificacion) values (79, 'Hughie', 'Bibendum.mp3', 19.1);
insert into CalificacionEntity (id, name, comentario, calificacion) values (80, 'Corena', 'SagittisNam.jpeg', 57.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (81, 'Lorrin', 'Nulla.ppt', 32.1);
insert into CalificacionEntity (id, name, comentario, calificacion) values (82, 'Morrie', 'SedJusto.mpeg', 61.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (83, 'Trip', 'TempusVelPede.avi', 90.0);
insert into CalificacionEntity (id, name, comentario, calificacion) values (84, 'Dorena', 'TellusSemperInterdum.jpeg', 85.9);
insert into CalificacionEntity (id, name, comentario, calificacion) values (85, 'Pip', 'UltricesPosuereCubilia.jpeg', 6.4);
insert into CalificacionEntity (id, name, comentario, calificacion) values (86, 'Lou', 'Donec.jpeg', 79.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (87, 'Ogdan', 'PurusPhasellus.avi', 10.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (88, 'Eydie', 'InHacHabitasse.mp3', 42.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (89, 'Gamaliel', 'AtVulputateVitae.xls', 15.3);
insert into CalificacionEntity (id, name, comentario, calificacion) values (90, 'Dareen', 'ALibero.xls', 14.2);
insert into CalificacionEntity (id, name, comentario, calificacion) values (91, 'Noam', 'Sed.mov', 43.8);
insert into CalificacionEntity (id, name, comentario, calificacion) values (92, 'Merrielle', 'Ut.xls', 85.1);
insert into CalificacionEntity (id, name, comentario, calificacion) values (93, 'Annalise', 'Amet.avi', 26.7);
insert into CalificacionEntity (id, name, comentario, calificacion) values (94, 'Laurice', 'LiberoConvallis.mp3', 10.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (95, 'Prentice', 'MassaDonecDapibus.mp3', 84.6);
insert into CalificacionEntity (id, name, comentario, calificacion) values (96, 'Henriette', 'ConsequatNullaNisl.ppt', 97.2);
insert into CalificacionEntity (id, name, comentario, calificacion) values (97, 'Francisca', 'RhoncusAliquam.tiff', 68.4);
insert into CalificacionEntity (id, name, comentario, calificacion) values (98, 'Joletta', 'Platea.avi', 72.4);
insert into CalificacionEntity (id, name, comentario, calificacion) values (99, 'Magnum', 'AtDolor.avi', 54.2);
insert into CalificacionEntity (id, name, comentario, calificacion) values (100, 'Jakie', 'Ante.ppt', 78.2);
delete from TrabajoEntity;
insert into TrabajoEntity (id, name, terminado) values (50, 'Ethelda', 0);
insert into TrabajoEntity (id, name, terminado) values (51, 'Torr', 0);
insert into TrabajoEntity (id, name, terminado) values (52, 'Murvyn', 0);
insert into TrabajoEntity (id, name, terminado) values (53, 'Mendie', 1);
insert into TrabajoEntity (id, name, terminado) values (54, 'Josee', 1);
insert into TrabajoEntity (id, name, terminado) values (55, 'Berthe', 1);
insert into TrabajoEntity (id, name, terminado) values (56, 'Corena', 0);
insert into TrabajoEntity (id, name, terminado) values (57, 'Feodor', 0);
insert into TrabajoEntity (id, name, terminado) values (58, 'Hakeem', 1);
insert into TrabajoEntity (id, name, terminado) values (59, 'Eirena', 1);
insert into TrabajoEntity (id, name, terminado) values (60, 'Timmy', 0);
insert into TrabajoEntity (id, name, terminado) values (61, 'Mariya', 1);
insert into TrabajoEntity (id, name, terminado) values (62, 'Fifine', 1);
insert into TrabajoEntity (id, name, terminado) values (63, 'Raleigh', 1);
insert into TrabajoEntity (id, name, terminado) values (64, 'Ernie', 0);
insert into TrabajoEntity (id, name, terminado) values (65, 'Barbabra', 1);
insert into TrabajoEntity (id, name, terminado) values (66, 'Tudor', 1);
insert into TrabajoEntity (id, name, terminado) values (67, 'Amandie', 0);
insert into TrabajoEntity (id, name, terminado) values (68, 'Lonnie', 1);
insert into TrabajoEntity (id, name, terminado) values (69, 'Hobart', 0);
insert into TrabajoEntity (id, name, terminado) values (70, 'Saunder', 0);
insert into TrabajoEntity (id, name, terminado) values (71, 'Lissy', 0);
insert into TrabajoEntity (id, name, terminado) values (72, 'Arlena', 0);
insert into TrabajoEntity (id, name, terminado) values (73, 'Hilliary', 1);
insert into TrabajoEntity (id, name, terminado) values (74, 'Norene', 0);
insert into TrabajoEntity (id, name, terminado) values (75, 'Korey', 0);
insert into TrabajoEntity (id, name, terminado) values (76, 'Patrica', 1);
insert into TrabajoEntity (id, name, terminado) values (77, 'Freida', 1);
insert into TrabajoEntity (id, name, terminado) values (78, 'Rora', 0);
insert into TrabajoEntity (id, name, terminado) values (79, 'Ludovika', 1);
insert into TrabajoEntity (id, name, terminado) values (80, 'Alon', 1);
insert into TrabajoEntity (id, name, terminado) values (81, 'Felix', 1);
insert into TrabajoEntity (id, name, terminado) values (82, 'Nikolai', 0);
insert into TrabajoEntity (id, name, terminado) values (83, 'Joleen', 1);
insert into TrabajoEntity (id, name, terminado) values (84, 'Madelene', 1);
insert into TrabajoEntity (id, name, terminado) values (85, 'Cris', 1);
insert into TrabajoEntity (id, name, terminado) values (86, 'See', 0);
insert into TrabajoEntity (id, name, terminado) values (87, 'Johnette', 0);
insert into TrabajoEntity (id, name, terminado) values (88, 'Toma', 1);
insert into TrabajoEntity (id, name, terminado) values (89, 'Glenda', 1);
insert into TrabajoEntity (id, name, terminado) values (90, 'Emilee', 1);
insert into TrabajoEntity (id, name, terminado) values (91, 'Otha', 1);
insert into TrabajoEntity (id, name, terminado) values (92, 'Nancey', 1);
insert into TrabajoEntity (id, name, terminado) values (93, 'Daffie', 0);
insert into TrabajoEntity (id, name, terminado) values (94, 'Eduino', 0);
insert into TrabajoEntity (id, name, terminado) values (95, 'Brannon', 0);
insert into TrabajoEntity (id, name, terminado) values (96, 'Juieta', 1);
insert into TrabajoEntity (id, name, terminado) values (97, 'Addison', 0);
insert into TrabajoEntity (id, name, terminado) values (98, 'Miguel', 1);
insert into TrabajoEntity (id, name, terminado) values (99, 'Mohammed', 0);
insert into TrabajoEntity (id, name, terminado) values (100, 'Edan', 1);
delete from EMPLEADOENTITY WHERE name= 'Juan Carlos';
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Job', 75.8, 3,50);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Cyrille', 99.5, 2,51);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Kin', 75.3, 2,52);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Ellis', 6.3, 1,53);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Howard', 43.9, 3,54);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Dorey', 62.1, 1,55);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Tyrus', 4.9, 3,56);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Gino', 84.6, 3,57);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Alessandro', 91.5, 1,58);
insert into EMPLEADOENTITY (name, calificacionPromedio, tipo,id) values ('Dalli', 41.6, 3,59);
delete from ClienteEntity;
insert into ClienteEntity (id, name) values (1, 'Wolfie McGirr');
insert into ClienteEntity (id, name) values (2, 'Bengt Scoffham');
insert into ClienteEntity (id, name) values (3, 'Della Edleston');
insert into ClienteEntity (id, name) values (4, 'Pennie Harriman');
insert into ClienteEntity (id, name) values (5, 'Aimee Baythorp');
insert into ClienteEntity (id, name) values (6, 'Kim Witcomb');
insert into ClienteEntity (id, name) values (7, 'Urban Duhig');
insert into ClienteEntity (id, name) values (8, 'Ophelia Poker');
insert into ClienteEntity (id, name) values (9, 'Penelope Hinckesman');
insert into ClienteEntity (id, name) values (10, 'Otho Bedingfield');
insert into ClienteEntity (id, name) values (11, 'Blane Basek');
insert into ClienteEntity (id, name) values (12, 'Kaitlynn Creasy');
insert into ClienteEntity (id, name) values (13, 'Allan Littleproud');
insert into ClienteEntity (id, name) values (14, 'Koralle Kimpton');
insert into ClienteEntity (id, name) values (15, 'Keelby Peepall');
insert into ClienteEntity (id, name) values (16, 'Gerrard Lorant');
insert into ClienteEntity (id, name) values (17, 'Ericha Streather');
insert into ClienteEntity (id, name) values (18, 'Lesley Cullinan');
insert into ClienteEntity (id, name) values (19, 'Donelle Morrow');
insert into ClienteEntity (id, name) values (20, 'Gregorius Brinded');
insert into ClienteEntity (id, name) values (21, 'Latrina Diano');
insert into ClienteEntity (id, name) values (22, 'Farley Sircomb');
insert into ClienteEntity (id, name) values (23, 'Aksel Mutlow');
insert into ClienteEntity (id, name) values (24, 'Lorri Ellyatt');
insert into ClienteEntity (id, name) values (25, 'Kiel Athy');
insert into ClienteEntity (id, name) values (26, 'Barnabe Zettler');
insert into ClienteEntity (id, name) values (27, 'Filip Bram');
insert into ClienteEntity (id, name) values (28, 'Waylon Noweak');
insert into ClienteEntity (id, name) values (29, 'Thor Barme');
insert into ClienteEntity (id, name) values (30, 'Sunshine Fassam');
insert into ClienteEntity (id, name) values (31, 'Herminia Startin');
insert into ClienteEntity (id, name) values (32, 'Frayda Tumbelty');
insert into ClienteEntity (id, name) values (33, 'Nikola Seals');
insert into ClienteEntity (id, name) values (34, 'Tobias Hinge');
insert into ClienteEntity (id, name) values (35, 'Enrico Bugg');
insert into ClienteEntity (id, name) values (36, 'Opal Hedlestone');
insert into ClienteEntity (id, name) values (37, 'Lawton Steward');
insert into ClienteEntity (id, name) values (38, 'Denys Adrian');
insert into ClienteEntity (id, name) values (39, 'Marillin Roussel');
insert into ClienteEntity (id, name) values (40, 'Francklin Stive');
insert into ClienteEntity (id, name) values (41, 'Adey Hrycek');
insert into ClienteEntity (id, name) values (42, 'Boothe Wroughton');
insert into ClienteEntity (id, name) values (43, 'Philippine Teece');
insert into ClienteEntity (id, name) values (44, 'Maryrose Cottem');
insert into ClienteEntity (id, name) values (45, 'Khalil Pritty');
insert into ClienteEntity (id, name) values (46, 'Malissia Brotherhead');
insert into ClienteEntity (id, name) values (47, 'Parnell Frape');
insert into ClienteEntity (id, name) values (48, 'Inesita Berni');
insert into ClienteEntity (id, name) values (49, 'Had Denkel');
insert into ClienteEntity (id, name) values (50, 'Moreen Chennells');
delete from PagoEntity;
insert into PagoEntity (id, idEmpleado, idSolicitud) values (1, 12, 13);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (2, 1, 2);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (3, 13, 13);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (4, 14, 15);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (5, 5, 5);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (6, 6, 6);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (7, 7, 7);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (8, 8, 8);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (9, 9, 9);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (10, 10, 10);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (11, 11, 11);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (12, 12, 12);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (13, 13, 13);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (14, 14, 14);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (15, 15, 15);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (16, 16, 16);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (17, 17, 17);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (18, 18, 18);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (19, 19, 19);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (20, 20, 20);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (21, 21, 21);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (22, 22, 22);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (23, 23, 23);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (24, 24, 24);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (25, 25, 25);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (26, 26, 26);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (27, 27, 27);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (28, 28, 28);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (29, 29, 29);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (30, 30, 30);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (31, 31, 31);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (32, 32, 32);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (33, 33, 33);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (34, 34, 34);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (35, 35, 35);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (36, 36, 36);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (37, 37, 37);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (38, 38, 38);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (39, 39, 39);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (40, 40, 40);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (41, 41, 41);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (42, 42, 42);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (43, 43, 43);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (44, 44, 44);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (45, 45, 45);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (46, 46, 46);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (47, 47, 47);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (48, 48, 48);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (49, 49, 49);
insert into PagoEntity (id, idEmpleado, idSolicitud) values (50, 50, 50);
delete from TarjetaDeCreditoEntity;
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (1, 'Granville', 'Simonel', 12, 13, 'Collier and Sons', '9/23/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (2, 'Rahal', 'Gong', 12, 12, 'Rempel-Herman', '6/2/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (3, 'Leelah', 'Crayk', 13, 31, 'Marks-Schiller', '4/25/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (4, 'Skelly', 'Bille', 41, 14, 'McLaughlin Group', '6/1/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (5, 'Merridie', 'Tofts', 15, 51, 'Bednar-Watsica', '6/15/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (6, 'Feliza', 'Vollam', 16, 16, 'Kris Inc', '2/8/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (7, 'Janifer', 'Scarth', 17, 16, 'Sauer-Crona', '8/11/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (8, 'Abran', 'Sandhill', 18, 8, 'Dach-Lind', '4/9/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (9, 'Batsheva', 'Knibbs', 29, 9, 'Block, Bailey and Harber', '2/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (10, 'Gerda', 'Cotterel', 10, 10, 'Klocko, Labadie and Schultz', '10/21/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (11, 'Miguel', 'Trousdale', 11, 11, 'Kiehn-Bernhard', '3/2/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (12, 'Helene', 'Fidilis', 12, 12, 'Runolfsdottir Group', '8/14/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (13, 'Dorotea', 'Pleavin', 13, 13, 'Kerluke Group', '6/16/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (14, 'Kenny', 'Bielfeldt', 14, 14, 'Huel-Goyette', '12/25/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (15, 'Stacey', 'Bullocke', 15, 15, 'Turcotte and Sons', '2/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (16, 'Geno', 'McCart', 16, 16, 'Wunsch LLC', '4/28/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (17, 'Nappie', 'Aspall', 17, 17, 'Ritchie, Ernser and O''Keefe', '9/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (18, 'Berni', 'Linzey', 18, 18, 'Stracke-Senger', '10/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (19, 'Patric', 'Dyer', 19, 19, 'Steuber, Crooks and Funk', '5/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (20, 'Caitrin', 'Shaudfurth', 20, 20, 'Bins-Carroll', '10/4/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (21, 'Raoul', 'Courtonne', 21, 21, 'Kertzmann, Bernier and Renner', '10/24/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (22, 'Thoma', 'Haestier', 22, 22, 'VonRueden-Boehm', '3/18/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (23, 'Britt', 'Osmant', 23, 23, 'Lowe-Christiansen', '1/5/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (24, 'Spenser', 'Colvill', 24, 24, 'Langworth and Sons', '11/21/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (25, 'Evangelina', 'Hadgraft', 25, 25, 'Mayert, Batz and Hand', '4/1/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (26, 'Maddalena', 'Gibbins', 26, 26, 'Conroy, Barton and Pollich', '6/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (27, 'Luther', 'Pert', 27, 27, 'Little-Bauch', '9/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (28, 'Henrieta', 'Cumo', 28, 28, 'Mayer and Sons', '6/19/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (29, 'Cathleen', 'Marzella', 29, 29, 'Hoeger Group', '7/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (30, 'Jonathon', 'Stops', 30, 30, 'Boyle, O''Hara and Buckridge', '8/22/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (31, 'Willa', 'Parlott', 31, 31, 'O''Reilly, Towne and McGlynn', '9/8/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (32, 'Alica', 'Kubicka', 32, 32, 'Batz-Schroeder', '7/27/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (33, 'Cesaro', 'Tivers', 33, 33, 'Schulist LLC', '12/2/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (34, 'Flem', 'Trimble', 34, 34, 'Ratke-Blanda', '9/20/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (35, 'Hadria', 'Hammerberg', 35, 35, 'Rempel, Harvey and Rice', '10/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (36, 'Nolan', 'Foale', 36, 36, 'Schultz, Bruen and Parisian', '6/10/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (37, 'Vina', 'Kenworthey', 37, 37, 'Williamson, Corkery and Daniel', '8/25/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (38, 'La verne', 'Leachman', 38, 38, 'Denesik-Gleason', '7/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (39, 'Doralin', 'Stove', 39, 39, 'Kuhn and Sons', '1/3/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (40, 'Link', 'Pickerin', 40, 40, 'Bosco-Connelly', '12/18/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (41, 'Rea', 'Sheldrick', 41, 41, 'Schmidt, Lockman and Schmidt', '5/12/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (42, 'Ludwig', 'Tolman', 42, 42, 'McKenzie-Mraz', '6/6/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (43, 'Francoise', 'Albin', 43, 43, 'Crooks-Ward', '3/29/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (44, 'Sheilakathryn', 'Guerrieri', 44, 44, 'Marvin, Swift and Wolff', '12/11/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (45, 'Amelita', 'Matushevich', 45, 45, 'McKenzie and Sons', '7/18/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (46, 'Kassi', 'Cail', 46, 46, 'Marks-Wunsch', '11/19/2016');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (47, 'Elberta', 'Rushman', 47, 47, 'Kunze-Moore', '8/21/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (48, 'Kirsten', 'Chaimson', 48, 48, 'Klein-Schneider', '1/20/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (49, 'Douglass', 'Hartley', 49, 49, 'Predovic-Rippin', '4/24/2017');
insert into TarjetaDeCreditoEntity (id, nombres, apellidos, numero, codigoSeguridad, compañia, fechaExpiracion) values (50, 'Ronnie', 'Auston', 50, 50, 'Pollich-O''Kon', '10/15/2016');
delete from OfertaEntity;
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (1, 10, 20, 'ABC2345', 'Traduccion ingles espanol',  '30% de descuento', '2016-11-13 14:57:53' );
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (2, 11, 21, 'ABC2645', 'Traduccion aleman frances',  '40% de descuento', '2016-11-14 14:57:55');
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (3, 12, 22, 'ABC2445', 'Correccion ingles espanol',  '50% de descuento', '2017-09-10 14:57:53');
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (4, 13, 23, 'ABD2345', 'Correccion frances ingles',  '60% de descuento', '2016-11-16 14:53:53');
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (5, 14, 24, 'ABC2145', 'Traduccion', '70% de descuento', '2017-11-17 14:47:29');
insert into OfertaEntity (id, cantidadactual, cantidadinicial, codigo, name, descripcion, fechavigencia) values (6, 1, 20, 'ABC2175', 'Traduccion', '40% de descuento', '2017-10-17 14:47:29');
delete from PropuestaEntity;
insert into PropuestaEntity (id, name, costo, oferta_id, estado) values (1, 'nombre1', 20.3, 1, 'ACEPTADA' );
insert into PropuestaEntity (id, name, costo, oferta_id, estado) values (2, 'nombre2', 21.6, 2, 'RECHAZADA');
insert into PropuestaEntity (id, name, costo, oferta_id, estado) values (3, 'nombre3', 22.9, 3, 'EN_REVISION');
insert into PropuestaEntity (id, name, costo, oferta_id, estado) values (4, 'nombre4', 23.4, 4, 'RECHAZADA');
insert into PropuestaEntity (id, name, costo, oferta_id, estado) values (5, 'nombre5', 24.3, 5, 'ACEPTADA');
